In [1]:
import random
from faker import Faker
import pandas as pd
from datetime import datetime, timedelta

# Faker Türkçe başlat (genel fallback için)
fake_tr = Faker("tr_TR")
Faker.seed(42)
random.seed(42)

# ----------------------
# Kültürel isim-soyisim havuzları
# ----------------------
name_pools = {
    "Japonya": {
        "male_first": ["Yuki", "Haruto", "Sota", "Ren", "Yuma", "Kaito", "Daiki", "Takumi", "Ryota", "Kazuya"],
        "female_first": ["Asuka", "Sakura", "Hina", "Miyu", "Yui", "Haruka", "Rina", "Aya", "Nanami", "Mei"],
        "last": ["Takahashi", "Kobayashi", "Tanaka", "Saito", "Yamamoto", "Kato", "Ito", "Fujimoto", "Shimizu", "Mori"]
    },
    "İngiltere": {
        "male_first": ["John", "James", "William", "George", "Thomas", "Edward", "Henry", "Charles", "Arthur", "David"],
        "female_first": ["Emily", "Olivia", "Jessica", "Sophie", "Isabella", "Amelia", "Charlotte", "Mia", "Ella", "Lucy"],
        "last": ["Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Evans", "Thomas", "Roberts", "Johnson"]
    },
    "Türkiye": {
        "male_first": ["Ahmet", "Mehmet", "Emre", "Can", "Burak", "Mert", "Kerem", "Okan", "Onur", "Deniz"],
        "female_first": ["Elif", "Aylin", "Zeynep", "Derya", "Selin", "Büşra", "Nazlı", "Ece", "Aslı", "Melis"],
        "last": ["Yılmaz", "Demir", "Şahin", "Kaya", "Çelik", "Koç", "Aydın", "Öztürk", "Arslan", "Taş"]
    },
    "Fransa": {
        "male_first": ["Lucas", "Gabriel", "Louis", "Jules", "Hugo", "Arthur", "Nathan", "Ethan", "Paul", "Léo"],
        "female_first": ["Emma", "Louise", "Chloé", "Manon", "Léna", "Jade", "Alice", "Camille", "Inès", "Sarah"],
        "last": ["Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Leroy", "Moreau", "Simon"]
    },
    "Almanya": {
        "male_first": ["Max", "Felix", "Paul", "Lukas", "Leon", "Jonas", "Elias", "Tim", "Finn", "Jan"],
        "female_first": ["Mia", "Emma", "Hannah", "Sofia", "Anna", "Lea", "Lina", "Marie", "Lena", "Amelie"],
        "last": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Hoffmann", "Schulz"]
    },
    "ABD": {
        "male_first": ["Michael", "James", "Robert", "John", "David", "William", "Joseph", "Charles", "Thomas", "Christopher"],
        "female_first": ["Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen"],
        "last": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Miller", "Davis", "Garcia", "Rodriguez", "Wilson"]
    },
     "Hindistan": {
        "male_first": ["Arjun", "Ravi", "Karan", "Raj", "Vikram", "Amit", "Sanjay", "Dev", "Anil", "Rahul"],
        "female_first": ["Priya", "Anjali", "Neha", "Sanya", "Kavita", "Divya", "Pooja", "Rina", "Sunita", "Maya"],
        "last": ["Sharma", "Patel", "Gupta", "Kumar", "Singh", "Mehta", "Joshi", "Reddy", "Choudhary", "Das"]
    },
    "Güney Kore": {
        "male_first": ["Min-Jun", "Ji-Hoon", "Joon", "Hyun", "Soo", "Dong-Hyun", "Tae-Hyun", "Seung", "Jae", "Woo"],
        "female_first": ["Ji-Young", "Soo-Jin", "Hye-Jin", "Min-Seo", "Eun-Ji", "Seo-Yeon", "Bo-Ra", "Na-Ra", "Yu-Jin", "Hana"],
        "last": ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Jo", "Yoon", "Im", "Shin"]
    },
    "Çin": {
        "male_first": ["Wei", "Jian", "Hao", "Lei", "Feng", "Ming", "Tao", "Jun", "Peng", "Qiang"],
        "female_first": ["Li", "Mei", "Xiu", "Lan", "Fen", "Ying", "Hua", "Jing", "Ting", "Na"],
        "last": ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou"]
    },
    "İspanya": {
        "male_first": ["Carlos", "Juan", "Miguel", "Javier", "Luis", "Antonio", "Diego", "Manuel", "Francisco", "Pablo"],
        "female_first": ["Maria", "Carmen", "Laura", "Ana", "Isabel", "Sofia", "Elena", "Lucia", "Marta", "Paula"],
        "last": ["Garcia", "Martinez", "Rodriguez", "Lopez", "Sanchez", "Perez", "Gomez", "Diaz", "Fernandez", "Moreno"]
    },
    "İtalya": {
        "male_first": ["Luca", "Marco", "Giovanni", "Andrea", "Francesco", "Matteo", "Alessandro", "Davide", "Stefano", "Antonio"],
        "female_first": ["Giulia", "Francesca", "Martina", "Sara", "Chiara", "Anna", "Alessia", "Valentina", "Elisa", "Federica"],
        "last": ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco"]
    },
    "Meksika": {
        "male_first": ["José", "Luis", "Juan", "Carlos", "Miguel", "Fernando", "Jesús", "Alejandro", "Jorge", "Manuel"],
        "female_first": ["María", "Guadalupe", "Juana", "Juana", "Carmen", "Ana", "Verónica", "Isabel", "Luisa", "Martha"],
        "last": ["Hernández", "García", "Martínez", "López", "González", "Pérez", "Sánchez", "Ramírez", "Cruz", "Flores"]
    }
}

# ----------------------
# Film isimleri kelime havuzları (ülkeye göre)
# ----------------------
movie_title_words = {
    "Japonya": ["Taiyō", "Yoru", "Kaze", "Senshi", "Yūrei", "Tabibito", "Unmei", "Hoshi", "Shizukesa", "Tsuki", "Hana", "Ken"],
    "İngiltere": ["Shadow", "Queen", "Storm", "Light", "Night", "Secret", "Dragon", "Fire", "Kingdom", "Battle", "Legacy", "Whisper"],
    "Türkiye": ["Gölge", "Kral", "Yol", "Aşk", "Gece", "Hayat", "Umutsuz", "Rüya", "Güneş", "Düş", "Sessizlik", "Kader"],
    "Fransa": ["Lumière", "Nuit", "Cœur", "Ombre", "Rêve", "Feu", "Sang", "Étoile", "Voix", "Secret", "Liberté", "Âme"],
    "Almanya": ["Schatten", "König", "Kampf", "Nacht", "Feuer", "Geist", "Licht", "Traum", "Blut", "Fluss", "Weg", "Seele"],
    "ABD": ["Shadow", "King", "Battle", "Night", "Fire", "Ghost", "Light", "Dream", "Blood", "River", "Path", "Soul"],
     "Hindistan": ["Dil", "Raat", "Sapna", "Dosti", "Aag", "Zindagi", "Prem", "Safar", "Khwaab", "Pyar", "Rang", "Jeevan"],
    "Güney Kore": ["Baram", "Bam", "Sarangi", "Haneul", "Gidae", "Bimil", "Sarang", "Bitnaneun", "Hearts", "Uri", "Chueok", "Saebyeok"],
    "Çin": ["Ri", "Ye", "Feng", "Zhan", "Ling", "Xin", "Qing", "Shan", "Hua", "Tian", "Yue", "Long"],
    "İspanya": ["Sombras", "Reina", "Tormenta", "Luz", "Noche", "Secreto", "Dragón", "Fuego", "Reino", "Batalla", "Legado", "Susurro"],
    "İtalya": ["Ombra", "Regina", "Tempesta", "Luce", "Notte", "Segreto", "Drago", "Fuoco", "Regno", "Battaglia", "Eredità", "Sussurro"],
    "Meksika": ["Sombra", "Reina", "Tormenta", "Luz", "Noche", "Secreto", "Dragón", "Fuego", "Reino", "Batalla", "Legado", "Susurro"]
}

# ----------------------
# Biyografi cümleleri
# ----------------------
bio_sentences = [
    "Uzun yıllar sinema sektöründe önemli projelerde yer aldı.",
    "Çeşitli ödüllere layık görüldü ve eleştirmenlerce beğenildi.",
    "Filmografisi geniş ve farklı türlerde eserleri bulunmakta.",
    "Kariyerine genç yaşta başladı ve birçok başarılı projeye imza attı.",
    "Sanat hayatında yenilikçi ve cesur çalışmalarıyla tanınır.",
    "Uluslararası festivallerde aldığı ödüllerle adından söz ettirdi.",
    "Yaratıcı yönetmenlik anlayışı ve detaycılığı ile bilinir.",
    "Drama ve komedi türlerinde ustalığını kanıtlamıştır.",
    "Sanat ve kültür dünyasında önemli bir figür olarak kabul edilir.",
    "Hayatı boyunca pek çok farklı rolde başarılı performanslar sergiledi.",
    "Sektörde saygın bir isim olup birçok genç yeteneğe ilham vermiştir.",
    "Film endüstrisinde yenilikçi tekniklerle öncü olmuştur.",
    "Kültürel çeşitliliği ve insan hikayelerini işler.",
    "Derin karakter analizleri ile tanınmaktadır.",
    "Her filmi büyük bir titizlikle yönetir.",
    "Doğal oyunculuğu ve sahne hakimiyetiyle izleyiciyi büyüler.",
    "Çekimleri zorlu coğrafyalarda gerçekleştiren deneyimli bir sanatçıdır.",
    "Toplumsal meselelere duyarlı projelerde yer almıştır.",
    "Klasik ve modern sinemayı harmanlayan özgün bir yönetmendir.",
    "Çalışmaları pek çok genç sinemacıya ilham kaynağı olmuştur.",
    "Duygusal yoğunluğu yüksek performanslarıyla övgü toplamıştır.",
    "Seslendirme ve dublajda da başarılı çalışmaları vardır.",
    "Sinema ve tiyatro arasında başarılı bir geçiş yapmıştır.",
    "Çok yönlü sanatçı kimliği ile tanınır.",
    "Film müziklerine özel önem verir ve işbirlikleri yapar."
]

# ----------------------
# Film açıklamaları cümleleri
# ----------------------
description_sentences = [
    "Film, izleyiciyi derin bir maceraya sürüklüyor.",
    "Konu, aşk ve dramın iç içe geçtiği bir hikayeyi anlatıyor.",
    "Yüksek tempolu aksiyon sahneleri ile dikkat çekiyor.",
    "Gerilim dolu sahneleri ile nefes kesen bir yapım.",
    "Sanatsal ve estetik açıdan başarılı bir film.",
    "Özgün senaryosu ve sürükleyici kurgusuyla öne çıkıyor.",
    "Görsel efektleriyle izleyiciyi büyülüyor.",
    "Duygusal derinliği ve karakter gelişimi ile izlenmeye değer.",
    "Kültürel öğeler ve tarihsel referanslarla zenginleştirilmiş.",
    "Sinema tarihine adını yazdıracak bir yapım.",
    "Sürükleyici senaryosu ve güçlü oyunculuklarla izlenmeli.",
    "Gizemli atmosferi ile izleyiciyi etkisi altına alıyor.",
    "Karakterler arası ilişkiler dikkat çekici şekilde işlenmiş.",
    "Unutulmaz sahneleriyle hafızalarda yer ediniyor.",
    "Mükemmel müzikleri ve sahne tasarımı ile öne çıkıyor.",
    "Toplumsal mesajlar içeren çarpıcı bir yapım.",
    "Sürükleyici temposu ve sürpriz sonuyla izleyiciyi şaşırtıyor.",
    "Psikolojik derinliği olan karakterlere odaklanıyor.",
    "Doğa ve insan ilişkisini estetik bir dille ele alıyor.",
    "Çarpıcı diyaloglar ve zekice kurgulanmış olay örgüsü var.",
    "Renk paleti ve sinematografisiyle dikkat çekiyor.",
    "Çocukluk anıları ve aile bağlarını merkezine alıyor.",
    "Tarihi olayları özgün bir perspektiften yorumluyor.",
    "Fantastik öğelerle gerçek dünyayı harmanlayan bir hikaye.",
    "Yerli kültür motiflerini başarılı şekilde yansıtıyor."
]

# ----------------------
# Rol başlıkları
# ----------------------

# Ana karakter rolleri
main_roles = [
    "Başrol oyuncusu",
    "Kahramanın arkadaşı",
    "Aşk ilgisi",
    "Polis dedektif",
    "Bilim insanı",
    "Dedektif yardımcısı",
    "Prens/prenses",
    "İsyancı lider",
    "Terapist",
    "Katil şüphelisi",
    "Yabancı ajan",
    "Gizemli kahin",
    "Suçlu lider",
    "Kurtarıcı",
    "Asker kahraman",
    "Zengin iş insanı",
    "Gazeteci",
    "Sanatçı",
    "Yargıç",
    "Doktor"
]

# Yan karakter rolleri
side_roles = [
    "Yardımcı oyuncu",
    "Kötü karakter",
    "Komik yan karakter",
    "Uzay kaşifi",
    "Gizemli yabancı",
    "Gazeteci",
    "Mahkeme savcısı",
    "Asker komutan",
    "Çiftçi",
    "Şehirli genç",
    "Müzisyen",
    "İş insanı",
    "Eski dost",
    "Yazar",
    "Kahveci",
    "Barmen",
    "Polis memuru",
    "Sekreter",
    "Kütüphane görevlisi",
    "Çocuk",
    "Sokak satıcısı",
    "Taksi şoförü",
    "Bahçıvan",
    "Otel görevlisi",
    "Müdür",
    "Sporcu",
    "Sosyal medya fenomeni"
]

# Ana mı yan mı rol seçimi yapan fonksiyon
def generate_role_for_character(is_main):
    if is_main == 1:
        return random.choice(main_roles)
    else:
        return random.choice(side_roles)


# ----------------------
# Yardımcı fonksiyonlar
# ----------------------

def culturally_consistent_name(nationality, gender):
    pool = name_pools.get(nationality)
    if pool:
        if gender == "Erkek":
            first_name = random.choice(pool["male_first"])
        elif gender == "Kadın":
            first_name = random.choice(pool["female_first"])
        else:
            first_name = random.choice(pool["male_first"] + pool["female_first"])
        last_name = random.choice(pool["last"])
        return first_name, last_name
    else:
        # Havuzda yoksa Faker Türkçe fallback
        if gender == "Erkek":
            return fake_tr.first_name_male(), fake_tr.last_name()
        elif gender == "Kadın":
            return fake_tr.first_name_female(), fake_tr.last_name()
        else:
            return fake_tr.first_name(), fake_tr.last_name()

def culturally_consistent_movie_title(country):
    words = movie_title_words.get(country)
    if words:
        count = random.randint(2, 4)
        return " ".join(random.sample(words, count))
    else:
        return fake_tr.sentence(nb_words=random.randint(2,4)).replace(".", "")

def generate_turkish_biography():
    count = random.randint(3, 6)
    return " ".join(random.sample(bio_sentences, count))

def generate_turkish_description():
    count = random.randint(2, 5)
    return " ".join(random.sample(description_sentences, count))

def generate_turkish_role():
    return random.choice(role_titles)

def random_date(start_year, end_year):
    start = datetime(start_year, 1, 1)
    end = datetime(end_year, 12, 31)
    delta = end - start
    random_days = random.randint(0, delta.days)
    return start + timedelta(days=random_days)

def generate_budget_boxoffice():
    budget = round(random.uniform(0.5e6, 300e6), 2)
    boxoffice = round(budget * random.uniform(0.5, 5.0), 2)
    return budget, boxoffice

# ----------------------
# Verilerin üretimi
# ----------------------

NUM_GENRES = 10
NUM_DIRECTORS = 80
NUM_MOVIES = 300
NUM_ACTORS = 500
NUM_USERS = 300
NUM_RATINGS = 2000
AVG_ACTORS_PER_MOVIE = 5

genre_list = [
    ("Aksiyon", "Yüksek enerjili ve çok sayıda hareket sahnesi içerir."),
    ("Komedi", "Hafif ve eğlenceli, mizahi içerikli filmler."),
    ("Dram", "Duygusal yoğunluk ve karakter odaklı hikayeler."),
    ("Korku", "Korkutucu ve gerilim dolu sahneler içerir."),
    ("Bilim Kurgu", "Geleceğe dair teknoloji ve uzay temaları."),
    ("Romantik", "Aşk ve ilişkiler üzerine odaklanır."),
    ("Gerilim", "Heyecan verici ve gerilim dolu olaylar."),
    ("Belgesel", "Gerçek olayları ve bilgileri anlatan yapımlar."),
    ("Animasyon", "Çizgi film ya da bilgisayar üretimi animasyonlar."),
    ("Fantastik", "Büyü, doğaüstü ve hayali dünyalar içerir."),
]

genres = []
for i, (name, desc) in enumerate(genre_list, 1):
    genres.append({
        "GenreID": i,
        "GenreName": name,
        "Description": desc
    })
genres_df = pd.DataFrame(genres)

nationalities = list(name_pools.keys())

directors = []
for director_id in range(1, NUM_DIRECTORS + 1):
    nationality = random.choice(nationalities)
    gender = random.choices(["Erkek", "Kadın", "Diğer"], weights=[0.45, 0.45, 0.1])[0]
    birth_date = random_date(1940, 1985)
    first_name, last_name = culturally_consistent_name(nationality, gender)
    directors.append({
        "DirectorID": director_id,
        "FirstName": first_name,
        "LastName": last_name,
        "Gender": gender,
        "BirthDate": birth_date.date(),
        "Nationality": nationality,
        "AwardsCount": random.randint(0, 20),
        "Biography": generate_turkish_biography()
    })
directors_df = pd.DataFrame(directors)

actors = []
for actor_id in range(1, NUM_ACTORS + 1):
    nationality = random.choice(nationalities)
    gender = random.choices(["Erkek", "Kadın", "Diğer"], weights=[0.45, 0.45, 0.1])[0]
    birth_date = random_date(1950, 2000)
    first_name, last_name = culturally_consistent_name(nationality, gender)
    actors.append({
        "ActorID": actor_id,
        "FirstName": first_name,
        "LastName": last_name,
        "Gender": gender,
        "BirthDate": birth_date.date(),
        "Nationality": nationality,
        "AwardsCount": random.randint(0, 10),
        "Biography": generate_turkish_biography()
    })
actors_df = pd.DataFrame(actors)

languages = {
    "Japonya": "Japonca",
    "İngiltere": "İngilizce",
    "Türkiye": "Türkçe",
    "Fransa": "Fransızca",
    "Almanya": "Almanca",
    "ABD": "İngilizce",
    "Hindistan": "Hintçe",
    "Güney Kore": "Korece",
    "Çin": "Çince",
    "İspanya": "İspanyolca",
    "İtalya": "İtalyanca",
    "Meksika": "İspanyolca"
}

countries = list(name_pools.keys())

movies = []
for movie_id in range(1, NUM_MOVIES + 1):
    country = random.choice(countries)
    language = languages.get(country, "İngilizce")
    release_year = random.randint(1970, 2023)
    genre = random.choice(genres)
    director = random.choice(directors)
    duration = random.randint(80, 180)
    budget, boxoffice = generate_budget_boxoffice()
    title = culturally_consistent_movie_title(country)
    movies.append({
        "MovieID": movie_id,
        "Title": title,
        "ReleaseYear": release_year,
        "DurationMinutes": duration,
        "Language": language,
        "Country": country,
        "Budget": budget,
        "BoxOffice": boxoffice,
        "Description": generate_turkish_description(),
        "GenreID": genre["GenreID"],
        "DirectorID": director["DirectorID"]
    })
movies_df = pd.DataFrame(movies)

movie_actors = []
for movie in movies:
    movie_id = movie["MovieID"]
    main_char_count = random.choice([1, 2])
    actor_ids = random.sample(range(1, NUM_ACTORS + 1), AVG_ACTORS_PER_MOVIE)
    for i, actor_id in enumerate(actor_ids):
        is_main = 1 if i < main_char_count else 0
        role = generate_role_for_character(is_main)
        movie_actors.append({
            "MovieID": movie_id,
            "ActorID": actor_id,
            "Role": role,
            "IsMainCharacter": is_main
        })

movie_actors_df = pd.DataFrame(movie_actors)


user_countries = ["Türkiye", "ABD", "İngiltere", "Fransa", "Almanya", "Japonya"]
users = []
for user_id in range(1, NUM_USERS + 1):
    nationality = random.choice(user_countries)
    gender = random.choices(["Erkek", "Kadın", "Diğer"], weights=[0.48, 0.48, 0.04])[0]
    birth_date = random_date(1960, 2010)
    reg_date = random_date(2015, 2025)
    first_name, last_name = culturally_consistent_name(nationality, gender)
    users.append({
        "UserID": user_id,
        "UserName": fake_tr.user_name(),
        "Email": fake_tr.email(),
        "Gender": gender,
        "BirthDate": birth_date.date(),
        "Country": nationality,
        "RegistrationDate": reg_date.date()
    })
users_df = pd.DataFrame(users)

ratings = []
for rating_id in range(1, NUM_RATINGS + 1):
    movie = random.choice(movies)
    user = random.choice(users)
    rating_date = random_date(movie["ReleaseYear"], 2025)
    ratings.append({
        "RatingID": rating_id,
        "MovieID": movie["MovieID"],
        "UserID": user["UserID"],
        "RatingValue": round(random.uniform(1.0, 10.0), 1),
        "Comment": generate_turkish_description(),
        "RatingDate": rating_date.date()
    })
ratings_df = pd.DataFrame(ratings)

In [2]:
# Sonuç: tüm tablolar df olarak hazır

# Örnek çıktı göstermek için:
print("Genres sample:")
genres_df.head()


# İstersen CSV olarak kaydetmek için:
# genres_df.to_csv("Genres.csv", index=False)
# directors_df.to_csv("Directors.csv", index=False)
# movies_df.to_csv("Movies.csv", index=False)
# actors_df.to_csv("Actors.csv", index=False)
# movie_actors_df.to_csv("MovieActors.csv", index=False)
# users_df.to_csv("Users.csv", index=False)
# ratings_df.to_csv("Ratings.csv", index=False)

Genres sample:

   GenreID    GenreName                                        Description
0        1      Aksiyon  Yüksek enerjili ve çok sayıda hareket sahnesi ...
1        2       Komedi       Hafif ve eğlenceli, mizahi içerikli filmler.
2        3         Dram    Duygusal yoğunluk ve karakter odaklı hikayeler.
3        4        Korku         Korkutucu ve gerilim dolu sahneler içerir.
4        5  Bilim Kurgu          Geleceğe dair teknoloji ve uzay temaları.

In [3]:
print("Directors sample:")
directors_df.head()

Directors sample:

,DirectorID,FirstName,LastName,Gender,BirthDate,Nationality,AwardsCount,Biography
0,1,Andrea,Esposito,Erkek,1964-09-03,İtalya,4,Seslendirme ve dublajda da başarılı çalışmalar...
1,2,Emily,Jones,Kadın,1942-11-07,İngiltere,6,Çekimleri zorlu coğrafyalarda gerçekleştiren d...
2,3,Manon,Leroy,Kadın,1977-08-20,Fransa,18,Uzun yıllar sinema sektöründe önemli projelerd...
3,4,William,Johnson,Erkek,1959-04-26,ABD,2,Kariyerine genç yaşta başladı ve birçok başarı...
4,5,Verónica,García,Kadın,1951-03-14,Meksika,17,Duygusal yoğunluğu yüksek performanslarıyla öv...

In [4]:
print("Movies sample:")
movies_df.head()

Movies sample:

,MovieID,Title,ReleaseYear,DurationMinutes,Language,Country,Budget,BoxOffice,Description,GenreID,DirectorID
0,1,Taiyō Ken Shizukesa Tabibito,2009,96,Japonca,Japonya,2.558253e+08,1.997606e+08,Sinema tarihine adını yazdıracak bir yapım. Fi...,9,52
1,2,Sang Voix Ombre,1997,160,Fransızca,Fransa,9.577913e+07,2.128742e+08,Toplumsal mesajlar içeren çarpıcı bir yapım. S...,10,51
2,3,Feng Ri,1994,99,Çince,Çin,8.689703e+07,3.847201e+08,Renk paleti ve sinematografisiyle dikkat çekiy...,6,54
3,4,Rüya Düş Umutsuz,2016,97,Türkçe,Türkiye,2.585670e+07,8.765662e+07,Mükemmel müzikleri ve sahne tasarımı ile öne ç...,8,56
4,5,Tian Shan,2022,125,Çince,Çin,6.810941e+07,1.642440e+08,Tarihi olayları özgün bir perspektiften yoruml...,8,50

In [5]:
print("Actors sample:")
actors_df.head()

Actors sample:

,ActorID,FirstName,LastName,Gender,BirthDate,Nationality,AwardsCount,Biography
0,1,Paul,Simon,Diğer,1951-11-11,Fransa,0,Doğal oyunculuğu ve sahne hakimiyetiyle izleyi...
1,2,Tim,Schmidt,Erkek,1989-02-08,Almanya,7,Derin karakter analizleri ile tanınmaktadır. S...
2,3,David,Davis,Erkek,1994-06-14,ABD,8,Her filmi büyük bir titizlikle yönetir. Filmog...
3,4,Finn,Müller,Erkek,1986-04-06,Almanya,10,Derin karakter analizleri ile tanınmaktadır. Ç...
4,5,Min-Seo,Jung,Kadın,1954-08-19,Güney Kore,8,Hayatı boyunca pek çok farklı rolde başarılı p...

In [6]:
print("MovieActors sample:")
movie_actors_df.head()

MovieActors sample:

   MovieID  ActorID                 Role  IsMainCharacter
0        1      197  Kahramanın arkadaşı                1
1        1       11         Bilim insanı                1
2        1       57        Asker komutan                0
3        1      424                Müdür                0
4        1        7   Komik yan karakter                0

In [7]:
print("Users sample:")
users_df.head()

Users sample:

,UserID,UserName,Email,Gender,BirthDate,Country,RegistrationDate
0,1,yildirimsatrettin,muhammetyaman@example.net,Kadın,1989-11-04,Almanya,2024-05-22
1,2,tarhanhasgul,zenginsavki@example.org,Kadın,1992-11-09,Almanya,2020-10-15
2,3,corlumestur,fedentevetoglu@example.org,Kadın,1965-07-07,Fransa,2015-09-24
3,4,unalsensoy,cbilgin@example.net,Kadın,1967-07-14,ABD,2016-12-07
4,5,abid26,sayin23@example.com,Kadın,2005-05-07,İngiltere,2019-08-04

In [8]:
print("Ratings sample:")
ratings_df.head()

Ratings sample:

,RatingID,MovieID,UserID,RatingValue,Comment,RatingDate
0,1,180,42,5.1,Sürükleyici temposu ve sürpriz sonuyla izleyic...,2007-06-24
1,2,11,32,7.1,Özgün senaryosu ve sürükleyici kurgusuyla öne ...,1982-04-23
2,3,271,7,3.9,"Film, izleyiciyi derin bir maceraya sürüklüyor...",1996-03-17
3,4,89,97,2.6,Gizemli atmosferi ile izleyiciyi etkisi altına...,2021-05-07
4,5,80,192,2.6,Tarihi olayları özgün bir perspektiften yoruml...,2018-10-01

In [9]:
# CSV olarak kayıt
genres_df.to_csv("genres.csv", index=False)
directors_df.to_csv("directors.csv", index=False)
actors_df.to_csv("actors.csv", index=False)
movies_df.to_csv("movies.csv", index=False)
movie_actors_df.to_csv("movie_actors.csv", index=False)
users_df.to_csv("users.csv", index=False)
ratings_df.to_csv("ratings.csv", index=False)

In [10]:
import pandas as pd
from datetime import datetime
import numpy as np

def df_to_sql_inserts(df, table_name):
    inserts = []
    for _, row in df.iterrows():
        columns = ", ".join(df.columns)
        values_list = []
        for col in df.columns:
            val = row[col]
            if pd.isna(val):
                values_list.append("NULL")
            elif isinstance(val, str):
                val_escaped = val.replace("'", "''")
                values_list.append(f"'{val_escaped}'")
            elif isinstance(val, (datetime, pd.Timestamp, np.datetime64)):
                values_list.append(f"'{pd.to_datetime(val).strftime('%Y-%m-%d')}'")
            else:
                values_list.append(str(val))
        values = ", ".join(values_list)
        insert = f"INSERT INTO {table_name} ({columns}) VALUES ({values});"
        inserts.append(insert)
    return inserts

# Tarih kolonlarının datetime formatına dönüştürülmesi
directors_df['BirthDate'] = pd.to_datetime(directors_df['BirthDate'])
actors_df['BirthDate'] = pd.to_datetime(actors_df['BirthDate'])
users_df['BirthDate'] = pd.to_datetime(users_df['BirthDate'])
users_df['RegistrationDate'] = pd.to_datetime(users_df['RegistrationDate'])
ratings_df['RatingDate'] = pd.to_datetime(ratings_df['RatingDate'])

# Insert sorgularını oluştur
all_inserts = []
all_inserts.extend(df_to_sql_inserts(genres_df, "Genres"))
all_inserts.extend(df_to_sql_inserts(directors_df, "Directors"))
all_inserts.extend(df_to_sql_inserts(actors_df, "Actors"))
all_inserts.extend(df_to_sql_inserts(movies_df, "Movies"))
all_inserts.extend(df_to_sql_inserts(movie_actors_df, "MovieActors"))
all_inserts.extend(df_to_sql_inserts(users_df, "Users"))
all_inserts.extend(df_to_sql_inserts(ratings_df, "Ratings"))

# Tüm insert sorgularını tek bir string olarak birleştir
sql_insert_script = "\n".join(all_inserts)

# Dosyaya yazdır (UTF-8 encoding ile)
with open("movie_db_inserts.sql", "w", encoding="utf-8") as f:
    f.write(sql_insert_script)